New feature
nklimovych/Lv-666.Salesforce pull request #30
Opened 2022-04-19 19:47 UTC by nklimovych

+ [ ] User is automatically (with God's help) assigned to the Configurator group

2022-04-20 09:27 UTC, Devillkiller requested changes

2022-04-20 09:27 UTC, Devillkiller commented on VoteProject/force-app/main/default/classes/AddUserToGroup.cls
> +public with sharing class AddUserToGroup implements Queueable {
Please add comments

2022-04-20 09:27 UTC, Devillkiller commented on VoteProject/force-app/main/default/classes/AddUserToGroup.cls
> +	private final String CONF = 'Configurator';
Please fix indentation and renamve variable with meaningful name

2022-04-20 09:27 UTC, Devillkiller commented on VoteProject/force-app/main/default/classes/AddUserToGroup.cls
> +        insert members;
Please add logic to handle errors

2022-04-20 09:27 UTC, Devillkiller commented on VoteProject/force-app/main/default/classes/CreateGroups.cls
> +    public static List<Group> createUserGroups(List<Campaign__c> campNew){
Please avoid using static methods and adjust variable names avoiding shorten names where not necessary

2022-04-20 09:27 UTC, Devillkiller commented on VoteProject/force-app/main/default/classes/CreateGroups.cls
>      public static void deleteUserGroups(List<Campaign__c> campDel){
Please update to avoid static methods

2022-04-20 09:27 UTC, Devillkiller commented on VoteProject/force-app/main/default/classes/VotingCampaignTriggerHandler.cls
> +        System.debug('afterDelete');
Please remove if not needed

2022-04-20 09:27 UTC, Devillkiller commented on VoteProject/force-app/main/default/triggers/VotingCampaignTrigger.trigger
> +trigger VotingCampaignTrigger on Campaign__c (after insert, after delete) {
Please add comments

2022-04-26 18:16 UTC, Devillkiller requested changes

2022-04-27 22:28 UTC, nklimovych commented
@Devillkiller 
All requested changes are done. Going to start work on tests. Sorry for so long!

2022-05-04 08:41 UTC, Devillkiller requested changes

2022-05-04 08:41 UTC, Devillkiller commented on VoteProject/force-app/main/default/classes/CreateGroups.cls
>          'Analyst'};
Fix formatting.

2022-05-04 08:41 UTC, Devillkiller commented on VoteProject/force-app/main/default/classes/CreateGroups.cls
> +            delete deleteSelectedGroups;
you may combine lines 57 and 58 into 1 line, like below:

delete [SELECT Name FROM Group WHERE Name IN :selectedGroups];

2022-05-04 08:41 UTC, Devillkiller commented on VoteProject/force-app/main/default/classes/CreateGroups.cls
> -//дописати інсерт конфігуратора
Avoid adding non-English comments

2022-05-04 08:41 UTC, Devillkiller commented on VoteProject/force-app/main/default/classes/VotingCampaignTriggerHandler.cls
> -// варто передивитись як в макса і внести корективи, не факт що це запрацює, була помилка в 5 рядку!!
Same

2022-05-20 09:16 UTC, merged