Add coordinates update automation (without advanced exceptions and tests)
nklimovych/Lv-666.Salesforce pull request #40
Opened 2022-05-03 23:08 UTC by KravkoP

This feature automates (with Apex Trigger and TriggerHandler Framework) the process of collecting Address information from VoteCampaignLocation__c object records, finding appropriate coordinates (latitude, longitude), and adding it to the Coordinates field in the related VoteCampaignLocation__c object records.

2022-05-04 10:19 UTC, Devillkiller requested changes

2022-05-04 10:19 UTC, Devillkiller commented on force-app/main/default/classes/AddMembersToPublicGroups.cls
> +        this.publicgroups = publicgroups;
Same comment as for previous PR

2022-05-04 10:19 UTC, Devillkiller commented on force-app/main/default/classes/AddMembersToPublicGroups.cls
> +        System.debug('AddMembersToPublicGroups Started...');
Delete if not needed

2022-05-04 10:19 UTC, Devillkiller commented on force-app/main/default/classes/GetCoordinatesFromAddresses.cls
> +public without sharing class GetCoordinatesFromAddresses implements Queueable, Database.AllowsCallouts {
Add comments

2022-05-04 10:19 UTC, Devillkiller commented on force-app/main/default/classes/GetCoordinatesFromAddresses.cls
> +                while (parser.nextToken() != null) {
this seems strange to me. what is the purpouse?

2022-05-04 10:19 UTC, Devillkiller commented on force-app/main/default/classes/PublicGroupsManager.cls
> +        System.debug('createPublicGroups method started...');
Delete if not needed

2022-05-04 10:19 UTC, Devillkiller commented on force-app/main/default/classes/SendEmails.cls
> +        this.address = address;
Avoid using same names

2022-05-04 10:19 UTC, Devillkiller commented on force-app/main/default/classes/VoteCampaignLocationsManager.cls
> +public without sharing class VoteCampaignLocationsManager {
Add comments

2022-05-04 10:19 UTC, Devillkiller commented on force-app/main/default/classes/VoteCampaignTriggerHandler.cls
> +        System.debug('VoteCampaignTriggerHandler started...');
Delete if not needed

2022-05-04 10:19 UTC, Devillkiller commented on force-app/main/default/triggers/VoteCampaignLocationTrigger.trigger
> +    if (Trigger.isUpdate) {
Avoid having any logic in tigger body. Move to trigger handler.

2022-05-11 14:27 UTC, Devillkiller requested changes

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/CreatePublicGroups.cls
> +        List<Id> groupsIds = new List<Id>(groupsMap.keySet());
You do not need to convert set to list to use it in SOQL query.
Also, there is no need to declare separate variable. You may have "groupsMap.keySet()" operation embedded into query itself, like below:

 [SELECT Id, Name, CreatedById FROM Group WHERE Id IN :groupsMap.keySet() AND Name LIKE '%Configurators'];

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/CreatePublicGroups.cls
> +        List<Group> groupsToAddMembers = [SELECT Id, Name, CreatedById FROM Group WHERE Id IN :groupsIds AND Name LIKE '%Configurators'];
You may pass SOQL query directly into arguments of "new ManagePublicGroupsMembers" constructor, like below:

new ManagePublicGroupsMembers(
     [SELECT Id, Name, CreatedBy ... ]
);

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/CreatePublicGroups.cls
> +        ID addMembersJobId = System.enqueueJob(addMembersJob);
If you have no plans to use returend job id, you may skip assignment block, and adjust whole constructions like below:

System.enqueueJob(
____new ManagePublicGroupsMembers(
________[SELECT Id, Name, CreatedBy ... ]
____);
);

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/CreatePublicGroups.cls
> +        //AsyncApexJob addMembersJob_Log = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :addMembersJobId];
Delete obsolete code

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/EmailManager.cls
> +        ID sendEmailsJobId = System.enqueueJob(sendEmailsJob);
Same as above

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/GetCoordinatesFromAddresses.cls
> +                //AsyncApexJob updCoordinatesJob_Log = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :updCoordinatesJobId];
Same as above

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/GetCoordinatesFromAddresses.cls
> +        Double geometryCoordinates = (Double) parsedJSON.get(fieldName);
No need to asign returned value into variable. Instead, return it right away (as in "parseJSON" function).

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/ManagePublicGroupsMembers.cls
> +                gm.UserOrGroupId = UserInfo.getUserId();
Instead of using user id and user email getters in loop, move them before the loop's body and save returned values into variables.

Having those values storred in variables will give you better performance.

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/ManagePublicGroupsMembers.cls
> +        String emailSubject = 'You have been added to public group ' + groupName + '.';
You may return concatenated value right away, avoiding having it storred in variable.

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/ManagePublicGroupsMembers.cls
> +        return emailBody;
Same here

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/PublicGroupsManager.cls
> +        ID createGroupsJobId = System.enqueueJob(createGroupsJob);
Same comment as above (related to id and block optimization)

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/SendEmails.cls
> +        for (Messaging.SendEmailResult res : results) {
No need to have this loop and to store email sending results, because you are not handling it.

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/UpdateVoteCampaignLocationCoordinates.cls
> +            FROM VoteCampaignLocation__c WHERE Id = :voteCampaignLocationId];
Fix formatting, like below:
... = [
_____SELECT ...
_____FROM ....
];

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/VoteCampaignLocationTriggerHandler.cls
> +            VoteCampaignLocationsManager.updateCoordinates(newLocations);
Same here. Execute coodinates calculation logic only for a subset.

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/VoteCampaignLocationsManager.cls
> +        ID getCoordinatesJobId = System.enqueueJob(getCoordinatesJob);
Same optimization needs to be done here.

2022-05-11 14:27 UTC, Devillkiller commented on force-app/main/default/classes/VoteCampaignTriggerHandler.cls
> +    /*
Fix indentation.

2022-05-11 17:25 UTC, KravkoP commented on force-app/main/default/classes/CreatePublicGroups.cls
> +        //AsyncApexJob addMembersJob_Log = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :addMembersJobId];
I thought to leave this code (commented) for debug needs

2022-05-12 14:04 UTC, KravkoP commented on force-app/main/default/classes/SendEmails.cls
> +        for (Messaging.SendEmailResult res : results) {
According to Apex docs Message.sendEmail() method returns **a list** of SendEmailResult. Simultaneously, i used item from the Result list in If statement and debug log

2022-05-13 09:43 UTC, merged